### ISSUE TITLE
运行备份报错，无法备份

### ISSUE THREAD

**Issue by qixiaoqi33** [tanzzj/yapi-cooler#5]
![image](https://user-images.githubusercontent.com/50603967/81250157-d98f8100-9052-11ea-9920-e4aac94eee4f.png)
如图，运行后报错，配置项如下
![image](https://user-images.githubusercontent.com/50603967/81250215-f926a980-9052-11ea-8d07-3895431d468e.png)

**Comment by qixiaoqi33** [comment]
![88](https://user-images.githubusercontent.com/50603967/81250396-77834b80-9053-11ea-8db9-7ce70522d4b3.png)

**Comment by tanzzj** [comment]
收到，我排查下

TanzJ

________________________________

**Comment by tanzzj** [comment]
> ![image](https://user-images.githubusercontent.com/50603967/81250157-d98f8100-9052-11ea-9920-e4aac94eee4f.png)
> 如图，运行后报错，配置项如下
> ![image](https://user-images.githubusercontent.com/50603967/81250215-f926a980-9052-11ea-8d07-3895431d468e.png)

检查一下域名配置是否正确，我看了一下应该是域名配多了两个字符，我这边下个版本增加多一点提示

**Comment by tanzzj** [comment]
请检查你的域名配置是否正确，下版本将增加更多明显的提示 @qixiaoqi33

**Comment by qixiaoqi33** [comment]
> 请检查你的域名配置是否正确，下版本将增加更多明显的提示 @qixiaoqi33

你好。刚我看了域名是正确的，备份时依然报这个错误

**Comment by tanzzj** [comment]
> > 请检查你的域名配置是否正确，下版本将增加更多明显的提示 @qixiaoqi33
> 
> 你好。刚我看了域名是正确的，备份时依然报这个错误

试一下最新版本V0.1.2，如果有异常的话，把所有日志都发出来，也可以联系邮箱im.tanzj@live.com
